### ISSUE TITLE
use ctx.state instead of ctx.locals

### ISSUE THREAD

**Issue by fundon** [dominicbarnes/koa-handlebars#11]
The `ctx.state` was added, start from koa@v0.14.

**Comment by dominicbarnes** [comment]
+1

I've been meaning to do this anyways, I'll work on this soon.

**Comment by dominicbarnes** [comment]
As of `0.5.2`, `ctx.state` is merged into the `locals` var. (`ctx.locals` is still considered, but it will be deprecated and dropped in the near future)
