### ISSUE TITLE
Partials file names are not allowed the character "-"

### ISSUE THREAD

**Issue by basickarl** [dominicbarnes/koa-handlebars#12]
InternalServerError: unable to render view: home-public because The partial nav-public could not be found

Apparantly it craches when the name of a partial file has the character - in it. An example:

nav-public.hbs <--- crashes
navpublic.hbs <--- does not crash(includes changing {{> nav-public }} to {{> navpublic }} in the view)

```
// project/views/home-public.hbs
{{> nav-public }}
```

```
// project/partials/nav-public.hbs
This is a partial
```

**Comment by dominicbarnes** [comment]
For partials, the filename is camel-cased, try `navPublic` instead.

**Comment by basickarl** [comment]
Does state in the docs it is a bit backwards, thanks!

**Comment by dominicbarnes** [comment]
If you don't want that behavior, you are able to override that option in your config. :)
