### ISSUE TITLE
Error if no partials directory exists

### ISSUE THREAD

**Issue by lancejpollard** [dominicbarnes/koa-handlebars#15]
koa-handlebars requires a `./partials` directory to exist, but it would be nice if we could leave it out.

https://github.com/dominicbarnes/koa-handlebars/blob/1a2ae3345a3e1a279b35bb940eccc2ed91512e85/lib/renderer.js#L312

**Comment by dominicbarnes** [comment]
Fixed with ceb6a5842a25aac99bac866322cc8d39387c7c44
