### ISSUE TITLE
Simple example for including your own helper

### ISSUE THREAD

**Issue by basickarl** [dominicbarnes/koa-handlebars#20]
I keep seeing the following in tutorials etc.:
```
Handlebars.registerHelper('myHelper', function (date) { // get minutes between date and now
    return 'something...';
});
```
Would be nice if you could proves an example of how to get this to work with `koa-handlebars`.

**Comment by dominicbarnes** [comment]
You can pass an object of helpers via the [`helpers` config](https://github.com/dominicbarnes/koa-handlebars#helpers-1)

```js
app.use(handlebars({
  defaultLayout: 'main',
  helpers: {
    myHelper: function (date) {
      return 'something...';
    }
  }
}));
```

**Comment by dominicbarnes** [comment]
I'll accept a PR that adds an example to the `README.md`
